# Generated by Django 5.0.2 on 2024-03-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
